version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: local-postgres-fairuz
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: clipvault

    volumes:
      - /home/fairuz/Go Language/postgres/
      - ./db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql # Path disesuaikan

  postgres_test:
    image: postgres:latest
    container_name: local-postgres-fairuz
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: test_admin
      POSTGRES_PASSWORD: test_root
      POSTGRES_DB: test_clipvault

    volumes:
      - /home/fairuz/Go Language/postgres/
      - ./db/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql # Path disesuaikan

volumes:
  postgres_data:
  postgres_test_data:
